---
deployment:
  tasks:
    - export DEPLOYPATH=/home/minekpbj/public_html/alexharris.design/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH